### ISSUE TITLE
The atrain_match project is based on the NN-CTTH?

### ISSUE THREAD

**Issue by manan15105411262** [foua-pps/atrain_match#2]
The atrain_match project is based on the paper "Neural network cloud top pressure and height for MODIS"

**Comment by manan15105411262** [comment]
Thanks for your reply.Finally you are here.That's wonderful!Recently,I'm reading your paper "Neural network cloud top pressure and height for MODIS",and it's very creative.If it is convenient,can you share the code of NN-CTTH algorithm.I want to learn it more.Thank you~

**Comment by ninahakansson** [comment]
If you are interested in neural networks I suggest you checkout the Keras module https://keras.io/.

Best Regards
Nina Håkansson

**Comment by manan15105411262** [comment]
Ok,thank you,nina. I have used the neural network for classification,but in cloud retrieval i don't know use it how use the calipso/cloudsat data to train?Could you give some suggestion?
