### ISSUE TITLE
AMSR2 support

### ISSUE THREAD

**Issue by danielphilipp** [foua-pps/atrain_match#9]
Hi,

for CCI+ validation we selected February and July 2019. Because AMSR-E is not active in 2019 we aggreed to use AMSR2 measurements onboard JAXA GCOM-W1 for LWP validation. AMSR2 is not implemented yet but I had a look at the data and they are quite comparable (HDF5 format). I can implement it and push it (maybe already this week because we need the validation soon) but I just wanted to ask for your opinion concerning the implementation:

As AMSR-E is already implemented I could implement AMSR2 by simply adapting the reader then running the AMSR-E chain (using the `AmsrObject()`). Do you think it makes sense to implement an own processing chain for AMSR2 (distinguishing between `amsr` and `amsr2` everywhere within the code) or could it be more practical for maintenance and future developments to minimize the number of code lines by just using the AMSR-E code after reading ? I don't see issues with the minimum effort solution, except it might not be that clear to useres that "amsr" can be AMSR-E or AMSR2.

Referres to PR #10 

Cheers,
Daniel

**Comment by ninahakansson** [comment]
Great initiative! Let's start with one chain and we can divide them later if needed. 

We could add an attribute in the match-up files with information if it is AMSR-E or AMSR-2. Or maybe better add an attribute to all the amsr/cloudsat/imager/caliop object which files where used in the matching. This can be a separate PR later.
